name: Bump version, commit and push tag
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'main'
jobs:
  bump_version:
    if: ${{ github.event.pull_request.head.ref }} == 'release/patch' || ${{ github.event.pull_request.head.ref }} == 'release/minor' || ${{ github.event.pull_request.head.ref }} == 'release/major'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
      # Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Install dependencies
      - run: npm install
      # Get the current version from package.json
      - name: Get the current version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      # Print the current version
      - run: echo "The current version is ${{ steps.package-version.outputs.current-version }}"
      - name: Match branch name
        run: |
              if ${{ github.event.pull_request.head.ref }} == 'release/patch'; then
                echo "RELEASE_TYPE=patch" >> $GITHUB_ENV
              elif ${{ github.event.pull_request.head.ref }} == 'release/minor'; then
                echo "RELEASE_TYPE=minor" >> $GITHUB_ENV
              elif ${{ github.event.pull_request.head.ref }} == 'release/major'; then
                echo "RELEASE_TYPE=major" >> $GITHUB_ENV
              fi
      - run: echo "The bump version is $RELEASE_TYPE"